version: '3'

services:
  db:
    restart: always
    container_name: oma_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=manifesto
      - POSTGRES_PASSWORD=manifesto
      - POSTGRES_DB=manifesto
    ports:
      - "5412:5432"
    volumes:
      - oma-db:/var/lib/postgresql/data-oma
  web:
    restart: always
    container_name: oma_web
    build: .
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
    ports:
      - "${PORT}:5000"
    user: "1000:1000"
    depends_on:
      - db

volumes:
  oma-db:
