version: '3.4'

services:
  db:
    restart: always
    container_name: oma_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=manifesto
      - POSTGRES_PASSWORD=manifesto
      - POSTGRES_DB=manifesto
    ports:
      - "5412:5432"
    volumes:
      - oma-db:/var/lib/postgresql/data
  migrate:
    restart: on-failure
    container_name: oma_migrate
    build:
      context: .
      target: pre
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    command: ash -c "flask db upgrade"
    volumes:
      - .:/app
    user: "1000:1000"
    depends_on:
      - db
  web:
    restart: always
    container_name: oma_web
    build:
      context: .
      target: pre
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
    ports:
      - "${PORT}:4000"
    user: "1000:1000"
    depends_on:
      - db
      - migrate

volumes:
  oma-db:
