version: '3.4'

services:
  db-test:
    restart: always
    container_name: oma_db_test
    image: postgres:alpine
    environment:
      - POSTGRES_USER=manifesto
      - POSTGRES_PASSWORD=manifesto
      - POSTGRES_DB=test_manifesto
    ports:
      - "5413:5432"
  test:
    restart: on-failure
    container_name: oma_web
    build:
      context: .
      target: dev
    command: ash -c "sh runtests.sh"
    volumes:
      - .:/app
    user: "1000:1000"
    depends_on:
      - db-test
