version: '3'

services:
  db-test:
    restart: always
    container_name: oma_db_test
    image: postgres:alpine
    environment:
      - POSTGRES_USER=manifesto
      - POSTGRES_PASSWORD=manifesto
      - POSTGRES_DB=test_manifesto
    ports:
      - "5413:5432"
    volumes:
      - oma-test-db:/var/lib/postgresql/data-oma-test
  test:
    restart: on-failure
    container_name: oma_web
    build: .
    command: ash -c "sh runtests.sh"
    volumes:
      - .:/app
    user: "1000:1000"
    depends_on:
      - db-test

volumes:
  oma-test-db:
