"""empty message

Revision ID: c725ff7bf214
Revises: 
Create Date: 2019-09-30 17:28:15.298692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c725ff7bf214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manifesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('political_party', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('election_date', sa.Date(), nullable=True),
    sa.Column('election_type', sa.String(length=64), nullable=True),
    sa.Column('geographical_area', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=8), nullable=True),
    sa.Column('uri', sa.String(length=256), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('num_proposals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_number', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('budget', sa.Boolean(), nullable=True),
    sa.Column('non_negotiable', sa.Boolean(), nullable=True),
    sa.Column('agents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id_manifesto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_manifesto'], ['manifesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    op.drop_table('manifesto')
    # ### end Alembic commands ###
